#!/bin/bash
set -eo pipefail

declare -a versions=(
	2.9.2
	2.9.3
	2.10.1
	2.10.2
	2.10.3
	2.10.4
	2.10.5
	2.10.6
	2.11.0
	2.11.1
	2.11.2
	2.11.4
	2.11.5
	2.11.6
	2.11.7
	2.11.8
)

for version in "${versions[@]}"
do
	rm -rf "$version"
	mkdir "$version"
	cat > "$version/Dockerfile" <<-EOD
		# This Dockerfile is generated by "update.sh"
		# Do not edit it locally - your changes will be lost!

		FROM abigail/scala:$version
		MAINTAINER Abigail <AbigailBuccaneer@users.noreply.github.com>

		ENV SBT_VERSION 0.13.11
		RUN apt-get update -y && \\
		    apt-get install -y --no-install-recommends apt-transport-https && \\
		    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823 && \\
		    echo "deb https://dl.bintray.com/sbt/debian /" > /etc/apt/sources.list.d/sbt.list && \\
		    apt-get update -y && apt-get install -y --no-install-recommends "sbt=\$SBT_VERSION" && \\
		    sbt exit && \\
		    rm /etc/apt/sources.list.d/sbt.list && \\
		    apt-get purge -y apt-transport-https && \\
		    apt-get clean -y && \\
		    rm -rf /var/lib/apt/lists/*
	EOD
done
